module.exports = {
  release:{
    cluster:{
      canRetry:"true",
      removeNodeErrorCount:"5",
      restoreNodeTimeout:"0",
      defaultSelector:"RR"
    },
    master:{
      host:"148.70.66.137",
      user:"root",
      password:"kenanCrazy3!",
      database:"mysql",
      acquireTimeout:"10000",
      waitForConnections:"true",
      connectionLimit:"10",
      queueLimit:"0"
    }
  },
  dev:{
    cluster:{
      canRetry:"true",
      removeNodeErrorCount:"5",
      restoreNodeTimeout:"0",
      defaultSelector:"RR"
    },
    master:{
      host:"148.70.66.137",
      user:"root",
      password:"kenanCrazy3!",
      database:"mysql",
      acquireTimeout:"10000",
      waitForConnections:"true",
      connectionLimit:"10",
      queueLimit:"0"
    }
  }
}

/*
      host:"47.254.18.39",
      user:"c14",
      password:"shelterC14!",
      database:"shelter",
      acquireTimeout:"10000",
      waitForConnections:"true",
      connectionLimit:"10",
      queueLimit:"0"
      */
